#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(list1):
    
    pos_count, neg_count,zero = 0, 0, 0
  
    # iterating each number in list
    for num in list1:
        
        # checking condition
        if num >= 1:
            pos_count += 1  #positive number
    
        elif num == 0:
            zero += 1  #counting zero's
        
        else:
            neg_count+=1  #negtive numbers
            
    a=pos_count/len(list1)
    b=neg_count/len(list1)
    c=zero/len(list1)
    print("{:.6f}\n{:.6f}\n{:.6f}".format(a,b,c))   #formating {:.6f} means 6 numbers after "."

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
